[env:m5stack-atom]
platform = espressif32
board = m5stack-atom
framework = arduino

monitor_speed = 115200

lib_deps =
  lemmingdev/ESP32-BLE-Gamepad @ ^0.7.3
  h2zero/NimBLE-Arduino @ ^2.2.1
  jasonlzt/FastLED